openapi: 3.0.3
info:
  title: GEGENLICHT Register
  description: |
    The GEGENLICHT register allows our team members to speed up the handling
    of visitors by directly displaying all reservations and allowing the usage
    of QR codes for loyalty cards and reservation handling. Furthermore, it 
    allows us to handle card payments by an integration of the SumUp Payment
    Switch API.
  version: v1.0.0
  contact:
    name: Unikino GEGENLICHT
    email: info@gegenlicht.net
    url: https://gegenlicht.net/kontakt
  license:
    name: European Publuc License 1.2
    url: https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt

servers:
  - url: http://localhost:8000
    description: Local Development Server
    
  - url: https://register.gegenlicht.net
    description: Official Instance

tags:
  - name: Articles
    description: API Endpoint for managing articles

  - name: Reservations
    description: API Endpoints for managing reservations

  - name: Ticketing
    description: API Endpoints for generating ticket and managing ticket types

  - name: Other
    description: API Endpoints which are not sortable into one of the other categories

components:
  securitySchemes:
    user-api:
      type: openIdConnect
      description: |
        Authenticate using OpenID Connect and exchange the `authorization_code`
        for a Token Set via the `/auth/token` route.
      openIdConnectUrl: https://register.gegenlicht.net/api/auth/.openid-configuration

    integration-api:
      type: apiKey
      name: api-key
      in: header

  schemas:
    Article:
      allOf:
        - $ref: '#/components/schemas/NewArticle'
        - required:
            - id
          properties:
            id:
              type: string
              format: uuid
    NewArticle:
      type: object
      required:
        - name
        - prices
        - color
      properties:
        name:
          type: string
        prices:
          type: object
          properties:
            members:
              type: number
              nullable: true
            guests:
              type: number
        color:
              type: string
              description: |
                A color representation in one of the following formats:
                  - hexcolor
                  - rgb
                  - hsl

paths:
  /articles:
    get:
      summary: Get all available articles
      tags:
        - Articles
      responses:
        200:
          description: Article List
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'

    put:
      summary: Create New Article
      tags:
        - Articles
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewArticle'
      responses:
        201:
          description: Article Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
      
  /articles/{articleID}:
    parameters:
      - in: path
        name: articleID
        required: true
        schema:
          type: string
          format: uuid

    get:
      summary: Get Article Information
      tags:
        - Articles
      responses:
        200:
          description: Article List
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
      
  
