name: lint
on: ["push", "pull_request"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
    golangci-lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: actions/setup-go@v5
              with:
                go-version: stable
            - uses: golangci/golangci-lint-action@v6
              with:
                version: v1.62
                only-new-issues: ${{ github.event_name == 'pull_request'}}
                args: --enable-all --no-config